### ISSUE TITLE
Off-by-one in the tile counter

### ISSUE THREAD

**Issue by DaKnig** [paul-arutyunov/vtGBte#1]
The first tile number is 1 instead of 0...

**Comment by paul-arutyunov** [comment]
Well, this meant to be number instead of index
"tile #1" means "tiles[0]", as intended
This is not critical, I can change this if this is confusing

**Comment by paul-arutyunov** [comment]
Do you think I should?

**Comment by DaKnig** [comment]
I think that it should be changed to match other tools and common usage. When I want to know the location of tile x in memory, I would rather use "x * sizeof(tile) + offset" than "(x-1) * sizeof(tile) + offset".
The tools I have seen - for example, GBTD - also do refer to the tiles in that manner.
Besides, zero-based numbering is a standard in programming and IMHO should be always used...

**Comment by paul-arutyunov** [comment]
Ok
*kill Lua*
